<p>I was recommended by a work colleague to <a href="https://www.blossomvehicleleasing.co.uk">Blossom Vehicle Leasing</a>, who is a good friend of the Director. He'd recently begun a lease from Blossom which went through very smoothly, however, the exact opposite can be said for mine.</p>

<p>Let me start from the beginning; I had been sourcing a new vehicle for some time, and based on the recommendation, I approached Blossom to provide various quotes. They were helpful and speedy in their responses, and provided me with an offer which was very good. We went backwards and forwards, ensuring that the car I spec'd up from the manufacture’s website was 100% the car that was going to be ordered, and subsequentially delivered. I was very specific in the model that I wanted for various reasons, an easy task for a "factory" ordered car ... or so I thought.</p>

<p>After ordering, I was told by Blossom that there was a 2.5 month wait while the car was "factory" made. For my situation, this was perfect. It provided me with enough time to sell my current car, releasing the funds to pay for the initial payment. To my amazement, a month before the expected delivery date, I was told my new car was ready for delivery. I was a little sceptical at how a "factory" made car could be pushed through the manufacture queue so fast, however, I didn't question it. Unfortunately, I'd not sold my current car, so the dealer agreed to hold delivery of the new car until it had sold. A few weeks later I'd agreed to sell my car on a specific date, so arranged for delivery of the new car a week earlier than originally planned. I'd planned it so I had no time without a car between selling and delivery, as I heavily relied on driving, for getting to work / seeing unwell parents.</p>

<p>When the delivery date arrived, a car pulled up to my delivery destination, and I knew as soon as I saw it that something wasn't right. I inspected the car, and as I thought, it was the incorrect spec - i.e. not the car I had specifically ordered. It amazes me that during the month this car sat at the dealer, not one person thought to verify the car was correct. I called Blossom to inform them of the mistake, to which they apologised and offered me three options; 1. Take the car that had arrived, at a "cheaper" rate (I'd already got a quote for the exact car that was delivered, and the monthly payment they offered as a "goodwill" was more than the original - so, not cheaper), 2. Wait for another 5 months (!!!) for a new car to be factory ordered and delivered, or 3. Cancel the order completely.</p>

<p>I wasn't happy with the car, and didn't want to wait 5 months, so Blossom began searching around for a similar spec'd car. Eventually, they'd found me a higher spec'd car, which, ultimately will cost me more in both the initial payment, and monthly payments. The car was sold to me with a custom painted black roof, which, I wanted to do anyway - all was looking good. Then, I was told that I'd need to go through all the funding process again, which ultimately means I needed to have a 14-day cooling off period. As frustrating as this was, it was beyond mine, and Blossom’s, control, so it had to be done.</p>

<p>As previously said, I didn't want any time without a car, so, with this fault being between Blossom and their Dealer, I requested, via various emails and phone calls, that Blossom should provide me with a hire car for the 14-day period. I was ignored on these multiple times, and spent the best part of an entire day trying to sort this. Two further days had passed with no transport, and we were on Friday - the day before having a very busy weekend helping move house - the Director had verbally agreed to provide a hire car, and had asked me to source one. Despite this not being my responsibility, I did this within half an hour to ensure this was sorted before the weekend. Friday dwindled away, and I had no communication what-so-ever from anyone at Blossom - I tried calling, emailing, and texting. The following Monday morning came and I received an email from the Director saying that his "work phone" is not picked up till Monday .. what a way to run your business, ignore your stranded customers whilst you have a nice weekend away. Talk about customer service. It gets worse …</p>

<p>It was another three days with no transport, and multiple phone calls where I was told key people were "busy" or "away", until eventually I gave in and phoned the Director to get written confirmation that they will refund me for the cost of the hire car. We agreed on a price, I ordered the hire car, and I sent across the VAT invoice which they required to refund the payment.</p>

<p>The 14 days from that day past, and I had transport for the entire time. However, I heard nothing from Blossom despite many emails requesting updates on the refund. All I received was new funding documents for the costs of the new car. After eventually speaking with another Director, I was told on multiple occasions that the payments would be sent "today". More day's past, and nothing was received.</p>

<p>With the 14 day's past, and the new car ready for delivery, I returned the hire car and took delivery of the new car. Further to my amazement, the new car that was delivered didn't have a black roof - I asked myself how does something like this happen? Regardless, I spoke with Blossom to verify that this was in fact the correct car, and took delivery. I asked them on the phone, and again via email, to investigate what had happened with the roof - and still to this day both requests have been ignored.</p>

<p>Now we come to the current day; I'm 7 days post-delivery, and 29 days post hire-car payment, and still I have not received a refund for the hire car, my emails are being ignored, and I’m being told key people are "busy" or "away". I've also still been ignored regarding the roof.</p>

<p>To summarise; Blossom will do everything in their power to get you through their door. They'll source a car for you, but, once you're through that door, the customer service, specifically from the Directors, will be next to nothing. They do not care about you as individuals, and will not go above and beyond to ensure their customers are happy, even in a case where there's a huge mistake.</p>

<p>Please consider all your options before using this company.</p>
