<p>The likes of Mark Zuckerberg and Bill Gates have both agreed that understanding how to code is the new literacy. Even non-techies are now getting involved, with singer Will.I.Am saying he’s currently taking classes. You have no excuses, If you’re reading this, then you obviously have some sort of inkling to learn to code.</p>
<p>We’re in 2013. Every day we depend on technology, from using our mobile phones to walking through electric doors, however, only a few of us know how to read and write code. “The whole limit in the system is there just aren’t enough people trained in these skills today” says Zuckerberg.</p>
<p>Getting started with coding may seem like a daunting task, but once you get your head around the basics, it’s actually pretty straight forward. Here are a 5 free useful resources that’ll get you started:</p>
<ul class="links">
    <li><a title="Codecademy" href="http://www.codecademy.com" target="_blank">Codecademy</a> :: A comprehensive resource for courses spanning over eight genres: APIs, Ruby, Python, JavaScript, jQuery, PHP, web fundamentals, or combine languages into projects.</li>
    <li><a title="TheCodePlayer" href="http://thecodeplayer.com/" target="_blank">TheCodePlayer</a> :: This holds documented presentations that fully explain how people built project from scratch. After you’ve learnt to code and have a project to show off, you can add it here!</li>
    <li><a title="Mozilla Developer Network" href="https://developer.mozilla.org/en-US/" target="_blank">Mozilla Developer Network</a> :: A resource-rich collection of documents about web development. These documents range from experts, to students just starting out.</li>
    <li><a title="Code/Racer" href="http://coderace.me" target="_blank">Code/Racer</a> :: For a less intensive method of learning to code, try out this racing-game-based-learning. Learn the code as fast as possible to get ahead! Other than the racing game, this site holds over 650 instructional videos.</li>
    <li><a title="HTML5 Rocks" href="http://www.html5rocks.com/en/" target="_blank">HTML5 Rocks</a> :: This is a one-stop guide to learning, and referencing HTML5. This site has been written by many contributors that work for Google, Adobe and a bunch of other places.</li>
</ul>
