<p>First of all, we need to go back to the year of 2001 where I was in my second year at <a title="Open the Henley-In-Arden High School website" href="http://www.henleyschool.com/" target="_blank">Henley-In-Arden High School</a>.</p>
<p>I had always been fascinated with music, particularly with playing the drums, and thrived to start a band. Whilst taking a music module at Henley, two other music-talented friends and I decided to create this band. We named it “Panini”. We use to practice our songs once a week during our lunch break, whilst in our music module, and when we had some spare time.</p>

<h3>A New Hobby</h3>
<p>We wanted a place on the internet to be able to start a following. Build an audience. At the time the best, and only, place for this was <a title="Open MySpace" href="http://www.myspace.com" target="_blank">MySpace</a>. I created us an account and instantly found a new hobby, one that I’m not so proud of now – customizing people’s MySpace pages. I found it incredibly rewarding modifying something that had the potential to be seen by so many others. In the end, I ended up customizing quite a few of my friends pages.</p>
<p>Whilst writing these very messy stylesheet hacks, it encouraged me to go to Google and do some more in-depth digging about the wider web. I often found myself coming home from school and sitting staring at my <a title="CRT Monitor" href="https://www.google.co.uk/search?q=crt+monitor&amp;tbm=isch" target="_blank">PC’s CRT monitor</a> for hours on end, sometimes until the early hours of the mornings. I thought I worked better at night… I paid the price for that the next day at school. But never learnt my lesson.</p>

<h3>Study Time</h3>
<p>Months of reading articles, tutorials, watching videos and trial &amp; error went by, building my new-found skills as a web programmer. I set myself the challenge of creating Panini a custom website. It was to hold profiles on each band member, our music, and music we liked.</p>

<h3>A New Problem</h3>
<p>Building the website, however, was only one part of my task. I had to find a way to get the website live and accessible. I was a student, and a high-school one at that, so money was extremely limited. I doubted that my mum was going to fund me to spend more hours staring at my PC – she already thought I was spending too much time in my room as it was. I took a job working in a local pub (<a title="The Bluebull, Henley" href="http://www.bluebellhenley.co.uk/" target="_blank">The Bluebell</a>, Henley-In-Arden) as a kitchen porter. I saved and saved until I could afford to buy my server. With my savings I bought a <a title="Images of the Dell Poweredge 2400" href="https://www.google.co.uk/search?q=Dell%20Poweredge%202400&amp;tbm=isch" target="_blank">Dell Poweredge 2400</a> server for just under £300 from a business that had recently entered administration. This is where the second part of my task came into play – I now had to learn how to configure a web server.</p>
<p>Learning to configure my web server was a painful process. I went through two or three hard drives in the process of accidentally clicking, or typing, the format command. In the end, although it may not have been secure and optimised, I had a web server that was running <a title="Wikipedia Article on Apache" href="https://en.wikipedia.org/wiki/Apache" target="_blank">Apache</a>, <a title="Wikipedia Article on PHP" href="https://en.wikipedia.org/wiki/PHP" target="_blank">PHP</a>, <a title="Wikipedia Article on MySQL" href="https://en.wikipedia.org/wiki/MySQL" target="_blank">MySQL</a>, an <a title="Wikipedia Article on Email Systems" href="https://en.wikipedia.org/wiki/Email_system" target="_blank">Emailing system</a>, and a <a title="Wikipedia Article on Domain Name Systems" href="https://en.wikipedia.org/wiki/Domain_Name_System" target="_blank">DNS </a>service. The last issue I had to overcome was why my <a title="Wikipedia Article on Internet Protocols" href="https://en.wikipedia.org/wiki/Internet_Protocol" target="_blank">Internet Protocol</a> (IP) address kept on changing every 24 hours – I was stumped by this for days until I read yet more articles on Google and found the cause was my Internet Service Provider (ISP) issuing me a dynamic IP address. I was swift to convince my mum to move to an ISP that allowed static IP’s – we moved to <a title="Eclipse Business Broadband" href="http://www.eclipse.net.uk/business-broadband" target="_blank">Eclipse Business Broadband</a>, and everything worked flawlessly.</p>

<h3>Putting it Live</h3>
<p>Now I had a server running 24/7 that was live on the internet, I put the new Panini website up and told my whole IT class about it. The feeling of creating, and hosting, something that I had made from the ground up gave me such a buzz. After a few days that buzz had gone, and I was hunting for my next “fix”. It turned out that my interest in web programming outweighed my interest in making music, so I decided to slowly add-on new features to the Panini website that had nothing to do with the band. Adding photos of classmates, videos, and even links to be able to use MSN Messenger which at the time was blocked by our school.</p>

<h3>Career Sorted</h3>
<p>I soon realised that I’d found what I wanted to do for my foreseeable future. Become a Web Developer. Whilst other friends were struggling to find what they wanted to focus on as a career, I seemed to have hit the jackpot with my choice being made naturally.</p>
<p>This brings me to the present day. I’m still working in Web and haven’t had a day yet where I feel as though this “Isn’t for me”. What I’d like for anyone reading this to take away is that, if you’re dedicated enough, you can achieve your goals no matter how much work is ahead of you. I spent hours, months, even years learning how to program for the web, I’m even still learning now and won’t stop until my career does, but I know that it was that dedication that’s got me here today. Just think where dedication can get you.</p>
