<p>As of January 16th 2013 <a title="Instagram" href="http://instagram.com" target="_blank">Instagram</a>‘s new <a title="Instagram's Terms of Service" href="http://instagram.com/about/legal/terms/updated/" target="_blank">terms of service</a> and <a title="Instagram's Privacy Policy" href="http://instagram.com/about/legal/privacy/updated/" target="_blank">privacy policy</a> will take effect. Some of the changes that have been made might make you think twice about signing up or continuing to use their service.</p>
<p>From the new terms of service:</p>
<blockquote><p>Some or all of the Service may be supported by advertising revenue. To help us deliver interesting paid or sponsored content or promotions, <strong>you agree that a business or other entity may pay us to display your username, likeness, photos (along with any associated metadata), and/or actions you take, in connection with paid or sponsored content or promotions, without any compensation to you</strong>. If you are under the age of eighteen (18), or under any other applicable age of majority, you represent that at least one of your parents or legal guardians has also agreed to this provision (and the use of your name, likeness, username, and/or photos (along with any associated metadata)) on your behalf.</p></blockquote>
<p>Basically what the above means is that Instagram can now effectively <strong>sell</strong> the use of your <strong>username</strong>, <strong>profile picture</strong>, <strong>photos</strong> and records of what you’ve <strong>liked</strong> or <strong>commented</strong> on to another company – like an <strong>advertiser</strong> – and they don’t have to pay you. And you can’t stop them.</p>
<p>The only way to stop them at the moment is to cancel your account as they give you no opt-in/opt-out feature.</p>

@include('pages.blog.sections.advert')

<p>A great alternative to Instagram is <a title="Flickr" href="http://www.flickr.com/" target="_blank">Flickr</a>. There is a <a title="Free the Photos" href="http://freethephotos.com/" target="_blank">pretty neat website</a> that allows you to easily transfer all of your photos from your Instagram account to your Flickr. The only caveat that Flickr has is with free accounts you’re only allowed to transfer 300mb of data a month, so if you’ve got more than 10,000 photos – it’ll take you a couple of months to transfer. You can upgrade to a paid account to lift those restrictions though.</p>
<p>All-in-all, I think Instagram might have just written its self a suicide note and published it to the world. If this doesn’t kill them, it’ll seriously batter their reputation.</p>
