- name: "Add ondrej Repository for PHP 7"
  apt_repository:
    repo: 'ppa:ondrej/php'
    update_cache: yes

- name: "Install PHP 7"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - php7.0-fpm
    - php7.0-cli
    - php7.0-mysql
    - php7.0-curl
    - php7.0-gd

- name: "Copy custom php-fpm.conf file"
  template:
    src: php-fpm.conf.j2
    dest: /etc/php/7.0/fpm/php-fpm.conf
    owner: root
    mode: 0600
  notify: php_restart

- name: "Copy custom www.conf file"
  template:
    src: pool.d/www.conf.j2
    dest: /etc/php/7.0/fpm/pool.d/www.conf
    owner: root
    mode: 0600
  notify: php_restart
