- name: nginx_stop
  service:
    name: nginx
    state: stopped

- name: nginx_start
  service:
    name: nginx
    state: started

- name: nginx_restart
  service:
    name: nginx
    state: restarted
