<?php

use Carbon\Carbon;

return [
    'posts' => [
        'victoria-jeffs' => [
            'title' => 'Victoria Jeffs',
            'subtitle' => 'Estate Agent',
            'icon' => 'fa fa-home',
            'date' => Carbon::createFromDate(2015, 1, 5),
            'introduction' => 'pages.projects.projects.victoria-jeffs.intro',
            'content' => 'pages.projects.projects.victoria-jeffs.content',
            'testimonial' => false,
            'link' => 'http://victoriajeffs.co.uk',
            'expired' => false,
            'hero' => 'assets/img/projects/victoria-jeffs/hero.jpg',
            'keywords' => [
                'Victoria',
                'Jeffs',
                'Content Management System',
                'CMS',
                'Property',
                'Estate Agent',
            ],
            'images' => [
                'assets/img/projects/victoria-jeffs/images/1.jpg',
                'assets/img/projects/victoria-jeffs/images/2.jpg',
                'assets/img/projects/victoria-jeffs/images/3.jpg',
                'assets/img/projects/victoria-jeffs/images/4.jpg',
            ],
        ],
        'php-warwickshire' => [
            'title' => 'PHP Warwickshire',
            'subtitle' => 'User Group',
            'icon' => 'fa fa-code',
            'date' => Carbon::createFromDate(2014, 10, 10),
            'introduction' => 'pages.projects.projects.php-warwickshire.intro',
            'content' => 'pages.projects.projects.php-warwickshire.content',
            'testimonial' => false,
            'link' => 'http://phpwarks.co.uk',
            'expired' => false,
            'hero' => 'assets/img/projects/php-warwickshire/hero.jpg',
            'keywords' => [
                'PHP',
                'User Group',
                'User',
                'Group',
                'Meetup',
                'Rugby',
                'Developers',
            ],
            'images' => [
                'assets/img/projects/php-warwickshire/images/1.jpg',
                'assets/img/projects/php-warwickshire/images/2.jpg',
            ],
        ],
        'a-m-electrical' => [
            'title' => 'A M Electrical',
            'subtitle' => 'Electrical Contractors',
            'icon' => 'fa fa-headphones',
            'date' => Carbon::createFromDate(2014, 10, 11),
            'introduction' => 'pages.projects.projects.a-m-electrical.intro',
            'content' => 'pages.projects.projects.a-m-electrical.content',
            'testimonial' => false,
            'link' => 'http://a-m-electrical.com',
            'expired' => false,
            'hero' => 'assets/img/projects/a-m-electrical/hero.jpg',
            'keywords' => [
                'Aaron',
                'Middleton',
                'Electrical',
                'Electrician',
            ],
            'images' => [
                'assets/img/projects/a-m-electrical/images/1.jpg',
                'assets/img/projects/a-m-electrical/images/2.jpg',
                'assets/img/projects/a-m-electrical/images/3.jpg',
                'assets/img/projects/a-m-electrical/images/4.jpg',
                'assets/img/projects/a-m-electrical/images/5.jpg',
                'assets/img/projects/a-m-electrical/images/6.jpg',
            ],
        ],
        'admin-panel' => [
            'title' => 'Admin Panel',
            'subtitle' => 'Content Management',
            'icon' => 'fa fa-cogs',
            'date' => Carbon::createFromDate(2014, 11, 10),
            'introduction' => 'pages.projects.projects.admin-panel.intro',
            'content' => 'pages.projects.projects.admin-panel.content',
            'testimonial' => false,
            'link' => false,
            'expired' => false,
            'hero' => 'assets/img/projects/admin-panel/hero.jpg',
            'keywords' => [
                'CMS',
                'Content Management System',
                'Packages',
                'Laravel',
            ],
            'images' => [
                'assets/img/projects/admin-panel/images/1.jpg',
                'assets/img/projects/admin-panel/images/2.jpg',
                'assets/img/projects/admin-panel/images/3.jpg',
                'assets/img/projects/admin-panel/images/4.jpg',
                'assets/img/projects/admin-panel/images/5.jpg',
            ],
        ],
        'shrek-alarm' => [
            'title' => 'Shrek Alarm',
            'subtitle' => 'Mobile Application',
            'icon' => 'fa fa-clock-o',
            'date' => Carbon::createFromDate(2013, 8, 8),
            'introduction' => 'pages.projects.projects.shrek-alarm.intro',
            'content' => 'pages.projects.projects.shrek-alarm.content',
            'testimonial' => false,
            'link' => false,
            'expired' => 'This application and website is no longer available',
            'hero' => 'assets/img/projects/shrek-alarm/hero.jpg',
            'keywords' => [
                'Shrek',
                'DreamWorks',
                'Alarm Clock',
                'Wake Up',
                'iOS',
                'Apple',
                'iPhone',
                'Android',
            ],
            'images' => [
                'assets/img/projects/shrek-alarm/images/1.jpg',
                'assets/img/projects/shrek-alarm/images/2.jpg',
            ],
        ],
        'blitz-games' => [
            'title' => 'Blitz Games',
            'subtitle' => 'Responsive Design',
            'icon' => 'fa fa-gamepad',
            'date' => Carbon::createFromDate(2013, 6, 12),
            'introduction' => 'pages.projects.projects.blitz-games.intro',
            'content' => 'pages.projects.projects.blitz-games.content',
            'testimonial' => false,
            'link' => 'http://blitzgames.com',
            'expired' => false,
            'hero' => 'assets/img/projects/blitz-games/hero.jpg',
            'keywords' => [
                'Blitz',
                'Games',
                'Responsive',
                'UX',
                'SEO',
                'CodeIgniter',
                'Portfolio',
            ],
            'images' => [
                'assets/img/projects/blitz-games/images/1.jpg',
                'assets/img/projects/blitz-games/images/2.jpg',
                'assets/img/projects/blitz-games/images/3.jpg',
                'assets/img/projects/blitz-games/images/4.jpg',
            ],
        ],
        'vuven' => [
            'title' => 'Vuven',
            'subtitle' => 'Rebrand',
            'icon' => 'fa fa-database',
            'date' => Carbon::createFromDate(2013, 4, 11),
            'introduction' => 'pages.projects.projects.vuven.intro',
            'content' => 'pages.projects.projects.vuven.content',
            'testimonial' => false,
            'link' => 'http://vuven.com',
            'expired' => false,
            'hero' => 'assets/img/projects/vuven/hero.jpg',
            'keywords' => [
                'Vuven',
                'Website',
                'Development',
                'Design',
                'Applications',
            ],
            'images' => [
                'assets/img/projects/vuven/images/1.jpg',
                'assets/img/projects/vuven/images/2.jpg',
                'assets/img/projects/vuven/images/3.jpg',
            ],
        ],
        'blitz-tech' => [
            'title' => 'BlitzTech',
            'subtitle' => 'Responsive Design',
            'icon' => 'fa fa-cog',
            'date' => Carbon::createFromDate(2013, 2, 14),
            'introduction' => 'pages.projects.projects.blitz-tech.intro',
            'content' => 'pages.projects.projects.blitz-tech.content',
            'testimonial' => false,
            'link' => false,
            'expired' => 'This website is no longer available',
            'hero' => 'assets/img/projects/blitz-tech/hero.jpg',
            'keywords' => [
                'Blitz',
                'Tech',
                'Technology',
                'Software',
                'Responsive',
                'Design',
                'Re-design',
                'CSS3',
                'HTML5',
            ],
            'images' => [
                'assets/img/projects/blitz-tech/images/1.jpg',
                'assets/img/projects/blitz-tech/images/2.jpg',
                'assets/img/projects/blitz-tech/images/3.jpg',
                'assets/img/projects/blitz-tech/images/4.jpg',
                'assets/img/projects/blitz-tech/images/5.jpg',
            ],
        ],
        'blitz-games-studios' => [
            'title' => 'Blitz Games Studios',
            'subtitle' => 'Redesigned Home Page',
            'icon' => 'fa fa-trophy',
            'date' => Carbon::createFromDate(2012, 12, 19),
            'introduction' => 'pages.projects.projects.blitz-games-studios.intro',
            'content' => 'pages.projects.projects.blitz-games-studios.content',
            'testimonial' => false,
            'link' => 'http://blitzgamesstudios.com',
            'expired' => false,
            'hero' => 'assets/img/projects/blitz-games-studios/hero.jpg',
            'keywords' => [
                'Home Page',
                'Re-design',
                'Full Screen',
                'Interactive',
                'Dropdown Menu',
                'Responsive',
            ],
            'images' => [
                'assets/img/projects/blitz-games-studios/images/1.jpg',
                'assets/img/projects/blitz-games-studios/images/2.jpg',
            ],
        ],
        'umberslade-adventure' => [
            'title' => 'Umberslade Adventure',
            'subtitle' => 'Outdoor Adventures',
            'icon' => 'fa fa-paw',
            'date' => Carbon::createFromDate(2012, 9, 1),
            'introduction' => 'pages.projects.projects.umberslade-adventure.intro',
            'content' => 'pages.projects.projects.umberslade-adventure.content',
            'testimonial' => false,
            'link' => 'http://umbersladeadventure.com',
            'expired' => false,
            'hero' => 'assets/img/projects/umberslade-adventure/hero.jpg',
            'keywords' => [
                'Outdoor Adventures',
                'Design',
                'Build',
                'HTML5',
                'CSS3',
                'Semantic Markup',
                'Adventure',
                'Playarea',
                'Children',
                'Days out',
            ],
            'images' => [
                'assets/img/projects/umberslade-adventure/images/1.jpg',
                'assets/img/projects/umberslade-adventure/images/2.jpg',
                'assets/img/projects/umberslade-adventure/images/3.jpg',
                'assets/img/projects/umberslade-adventure/images/4.jpg',
            ],
        ],
        'coca-cola' => [
            'title' => 'Coca-Cola Promotion',
            'subtitle' => 'User Interface',
            'icon' => 'fa fa-hand-paper-o',
            'date' => Carbon::createFromDate(2012, 1, 1),
            'introduction' => 'pages.projects.projects.coca-cola.intro',
            'content' => 'pages.projects.projects.coca-cola.content',
            'testimonial' => false,
            'link' => false,
            'expired' => 'This website is no longer available',
            'hero' => 'assets/img/projects/coca-cola/hero.jpg',
            'keywords' => [
                'Coca Cola',
                'NFL',
                'Super Bowl',
                '46',
                '2012',
                'Promotion',
                'Interactive',
                'User Interface',
                'Software',
            ],
            'images' => [
                'assets/img/projects/coca-cola/images/1.jpg',
                'assets/img/projects/coca-cola/images/2.jpg',
                'assets/img/projects/coca-cola/images/3.jpg',
                'assets/img/projects/coca-cola/images/4.jpg',
            ],
        ],
        'well-forged-films' => [
            'title' => 'Well Forged Films',
            'subtitle' => 'Movie Portfolio',
            'icon' => 'fa fa-video-camera',
            'date' => Carbon::createFromDate(2011, 12, 21),
            'introduction' => 'pages.projects.projects.well-forged-films.intro',
            'content' => 'pages.projects.projects.well-forged-films.content',
            'testimonial' => false,
            'link' => false,
            'expired' => 'This website is no longer available',
            'hero' => 'assets/img/projects/well-forged-films/hero.jpg',
            'keywords' => [
                'Film',
                'Well Forged',
                'Production Company',
            ],
            'images' => [
                'assets/img/projects/well-forged-films/images/1.jpg',
                'assets/img/projects/well-forged-films/images/2.jpg',
                'assets/img/projects/well-forged-films/images/3.jpg',
            ],
        ],
    ],
];
