<!DOCTYPE html>
<html lang="en-US">
	<head>
		<meta charset="utf-8">
	</head>
	<body>
		<p>
			This message has been auto-generated by the server at {{ $site }}. 
			It displays important information that has derived from the 
			interest form.
		</p>
		<p>
			<strong>Email: </strong> {{ $email }}<br />
			<strong>IP: </strong> {{ $ip }}<br />
			<strong>Sent: </strong> {{ $sent }}
		</p>
	</body>
</html>
