- name: "Stat for hush login"
  stat:
    path: "/home/{{ system_user }}/.hushlogin"
  register: hushlogin

- name: "Update apt's cache"
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: "Install packages"
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - unzip

- name: "Create group"
  group:
    name: "{{ system_group }}"
    state: present

- name: "Create user"
  user:
    name: "{{ system_user }}"
    shell: /bin/bash
    groups: "{{ system_group }}"

- name: "Make the login quiet"
  template:
    src: .hushlogin.j2
    dest: "/home/{{ system_user }}/.hushlogin"
    owner: "{{ system_user }}"
    mode: 0600
  when: not hushlogin.stat.exists
